import argparse
import pickle
import re
from pathlib import Path
from typing import Any, Dict, List
from urllib.parse import urlparse

from niltype import Nil
from d42.declaration.types import DictSchema

from openapi_processor import OpenAPIProcessor


def _safe_name(name: str) -> str:
    name = (name or "").strip()
    if not name:
        return "unnamed"
    name = re.sub(r"[^\w\-]+", "_", name)
    return name


def _safe_identifier(name: str) -> str:
    ident = re.sub(r"[^0-9a-zA-Z_]", "_", str(name or ""))
    if not ident:
        ident = "builder"
    if ident[0].isdigit():
        ident = "_" + ident
    return ident


def _derive_service_name(source: str, is_url: bool) -> str:
    if is_url:
        parsed = urlparse(source)
        host = parsed.netloc or parsed.path
        return _safe_name(host)
    p = Path(source)
    return _safe_name(p.stem or "service")


def _make_var_name_from_class(cname: str) -> str:
    if not cname:
        return _safe_identifier(cname)
    var = re.sub(r"[^0-9a-zA-Z_]", "_", cname)
    if var and var[0].isdigit():
        var = "_" + var
    if not var:
        var = _safe_identifier(cname)
    return var


def _write_loader_py(path: Path, kind: str, class_names: List[str]) -> None:
    """
    Generates a loader that reads schema_payload.pkl (dict class_name -> schema),
    calls generate_schema_builders_from_map and assigns variables.
    """
    var_lines: List[str] = []
    assign_lines: List[str] = []
    export_names: List[str] = []

    for cname in class_names:
        var_name = _make_var_name_from_class(cname)
        var_lines.append(f"{var_name}: Optional[type] = None")
        assign_lines.append(f'    {var_name} = _builders.get("{cname}")')
        export_names.append(var_name)

    tpl = f'''# Autogenerated builder module for {kind}
from pathlib import Path
import pickle
from typing import Optional, List, Dict

from common_ground import generate_schema_builders_from_map

_base = Path(__file__).parent
_payload_p = _base / "schema_payload.pkl"

_payload: Dict = {{}}
if _payload_p.exists():
    try:
        with _payload_p.open("rb") as _fh:
            _payload = pickle.load(_fh)
    except Exception:
        _payload = {{}}

{chr(10).join(var_lines)}

_builders: Dict[str, type] = {{}}
if _payload:
    try:
        _builders = generate_schema_builders_from_map(_payload)
    except Exception:
        _builders = {{}}

{chr(10).join(assign_lines)}

__all__ = [{", ".join(f'"{n}"' for n in export_names)}]
'''
    path.write_text(tpl, encoding="utf-8")


def generate(source: str, *, output_dir: Path | str = Path("generated")) -> Path:
    out_base = Path(output_dir)
    out_base.mkdir(parents=True, exist_ok=True)

    processor = OpenAPIProcessor()
    is_url = bool(urlparse(source).scheme and urlparse(source).netloc)
    if is_url:
        schema_list = processor.process_openapi_url(source)
    else:
        schema_list = processor.process_openapi_file(Path(source))

    # aggregation: prefix_pascal -> {"sds": [SchemaData,...], "payload": {class_name: schema}}
    groups: Dict[str, Dict[str, Any]] = {}
    for sd in schema_list:
        prefix = getattr(sd, "schema_prefix", None) or getattr(sd, "schema_prefix_humanized", None) or getattr(sd, "operation_id", None) or "Generated"
        grp = groups.setdefault(prefix, {"sds": [], "payload": {}})
        grp["sds"].append(sd)

    service_name = _derive_service_name(source, is_url)
    service_dir = out_base / service_name
    service_dir.mkdir(parents=True, exist_ok=True)

    for prefix, grp in groups.items():
        sds: List[Any] = grp["sds"]
        endpoint_dir = service_dir / prefix
        endpoint_dir.mkdir(parents=True, exist_ok=True)

        payload: Dict[str, Any] = {}

        # Collect all response schemas from all SDs (including different statuses).
        for sd in sds:
            responses_container = getattr(sd, "response_schema_d42", None)
            if responses_container is not None:
                key = f"{prefix}Response{sd.status}"
                if key not in payload:
                    payload[key] = responses_container

        # helper: determine whether sd has a successful 2xx status
        def _sd_has_success(sd_obj: Any) -> bool:
            rc = getattr(sd_obj, "responses_schema_d42", None) or getattr(sd_obj, "responses", None)
            if isinstance(rc, DictSchema):
                try:
                    keys = rc.props.keys
                    if keys is Nil or not isinstance(keys, dict):
                        return False
                    for status in keys.keys():
                        try:
                            ival = int(status)
                            if 200 <= ival < 300:
                                return True
                        except Exception:
                            if isinstance(status, str) and status.startswith("2"):
                                return True
                except Exception:
                    return False
            elif isinstance(rc, dict):
                for status in rc.keys():
                    try:
                        ival = int(status)
                        if 200 <= ival < 300:
                            return True
                    except Exception:
                        if isinstance(status, str) and status.startswith("2"):
                            return True
            else:
                # if there is a single response_schema and it's not empty — consider it successful by default
                single = getattr(sd_obj, "response_schema_d42", None) or getattr(sd_obj, "response_schema", None)
                if single is not None:
                    return True
            return False

        # Find sd with a successful status (2xx), otherwise take the first one
        sd_success = None
        for sd in sds:
            if _sd_has_success(sd):
                sd_success = sd
                break
        if sd_success is None and sds:
            sd_success = sds[0]

        # For Request/Queries/Headers — take schemas only from sd_success
        if sd_success is not None:
            req_schema = getattr(sd_success, "request_schema_d42", None) or getattr(sd_success, "request_schema", None)
            if req_schema is not None:
                payload[f"{prefix}Request"] = req_schema

            q_schema = getattr(sd_success, "queries_schema_d42", None) or getattr(sd_success, "queries_schema", None)
            if q_schema is not None:
                payload[f"{prefix}Queries"] = q_schema

            h_schema = getattr(sd_success, "request_headers_d42", None) or getattr(sd_success, "request_headers", None)
            if h_schema is not None:
                payload[f"{prefix}Headers"] = h_schema

        # Save payload to a file
        payload_path = endpoint_dir / "schema_payload.pkl"
        with payload_path.open("wb") as fh:
            pickle.dump(payload, fh)

        # Partition names by target files
        request_names = [n for n in payload.keys() if n.endswith("Request")]
        queries_names = [n for n in payload.keys() if n.endswith("Queries")]
        headers_names = [n for n in payload.keys() if n.endswith("Headers")]
        response_names = [n for n in payload.keys() if n.startswith(prefix + "Response")]

        # deduplicate while preserving order
        def uniq(seq: List[str]) -> List[str]:
            seen = set()
            out: List[str] = []
            for v in seq:
                if v not in seen:
                    seen.add(v)
                    out.append(v)
            return out

        request_names = uniq(request_names)
        queries_names = uniq(queries_names)
        headers_names = uniq(headers_names)
        response_names = uniq(response_names)

        if request_names:
            _write_loader_py(endpoint_dir / "request.py", kind="request", class_names=request_names)
        if queries_names:
            _write_loader_py(endpoint_dir / "queries.py", kind="queries", class_names=queries_names)
        if headers_names:
            _write_loader_py(endpoint_dir / "headers.py", kind="headers", class_names=headers_names)
        if response_names:
            _write_loader_py(endpoint_dir / "response.py", kind="response", class_names=response_names)

        init_path = endpoint_dir / "__init__.py"
        if not init_path.exists():
            init_path.write_text("# package for endpoint builders\n", encoding="utf-8")

    svc_init = service_dir / "__init__.py"
    if not svc_init.exists():
        svc_init.write_text("# package for service builders\n", encoding="utf-8")

    return service_dir


def main():
    parser = argparse.ArgumentParser(description="Process OpenAPI schema and generate builders package")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument('--file', type=str, help='Path to OpenAPI file (JSON or YAML)')
    group.add_argument('--url', type=str, help='URL to OpenAPI schema')
    parser.add_argument('--out', type=str, default="generated", help='Output base directory')
    args = parser.parse_args()

    source = args.file if args.file else args.url
    out = Path(args.out)
    service_dir = generate(source, output_dir=out)
    print(f"Generated builders under: {service_dir.resolve()}")


if __name__ == "__main__":
    main()
